server: 
  port: 8888

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false    servlet:      content-type: text/html
  resources: 
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: scott
    password: tiger
mybatis: 
  mapper-locations: Mapper.xml
  type-aliases-package: com.example.demo.Mapper
  
  